name: Bug Report
description: Create a report to help us improve Lingarr
title: '[BUG] Provide a descriptive title'
labels: 
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information below.

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: "Provide a detailed description of the issue, steps to reproduce, and expected vs actual behavior"
      placeholder: "Describe the issue here..."
      
  - type: textarea
    id: context
    attributes:
      label: Screenshots or Additional Context
      description: Provide any additional context and screenshots, docker compose conffigurations here to help us solve this issue.
    validations:
      required: false