name: Bug Report
description: Create a report to help us improve Lingarr
title: 'Bug report'
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information below.

  - type: input
    id: title
    attributes:
      label: Short summary of the issue
      placeholder: "Provide a descriptive title"

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: "Provide a detailed description of the issue, steps to reproduce, and expected vs actual behavior"
      placeholder: "Describe the issue here..."