blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/lingarr-translate/lingarr/discussions/categories/ideas-feature-requests
    about: Suggest new features and improvements for this project.